
#
# This LookML file was generated by AtScale on 2022-01-25T16:35:46.260476Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_AL

connection: "arthur_lookerdemo"
label: "Workshop_AL"


include: "/views/Workshop__AL/Workshop__AL.view.lkml"


explore: Workshop_AL {
  label: "Workshop_AL"
}

